### ISSUE TITLE
Top Level Torch Compile Issue Tracker

### ISSUE THREAD

**Issue by drisspg** [pytorch-labs/float8_experimental#195]
# Summary
This issue is used to track multiple issues encountered with torch.compile for Float8Tensor

### Sub-Issues/Pull Requests
* [x] PR to add subclass at graph_boundary: https://github.com/pytorch-labs/float8_experimental/pull/196
* [ ] ISSUE: https://github.com/pytorch-labs/float8_experimental/issues/223
* [ ] PR: The min cut partitioner does not want to recmpute weight cast: https://github.com/pytorch-labs/float8_experimental/issues/185 

### Sub-Issues/Pull Requests
* [x] ISSUE: https://github.com/pytorch/pytorch/issues/117115
	* [x] PR: https://github.com/pytorch/pytorch/pull/118191
* [ ] ISSUE: https://github.com/pytorch/pytorch/issues/117901
* [ ] ISSUE: https://github.com/pytorch/pytorch/issues/117662
- [x] ISSUE: https://github.com/pytorch/pytorch/issues/117596
- [x] ISSUE: https://github.com/pytorch/pytorch/issues/117652 (not blocking, I forgot to push my changes to the PR)
- [x] PR: https://github.com/pytorch/pytorch/pull/117666
- [x] PR: https://github.com/pytorch/pytorch/pull/117667
- [ ] ISSUE: https://github.com/pytorch/pytorch/issues/118211

**Comment by vkuzo** [comment]
closing this since this seems done, but please feel free to reopen if needed
